import type { Level, Listening, Question, Reading } from './types';
import { source } from './metadata';

function article(level: Level, title: string, text: string, translation: string, question: Question): Reading {
  return { id: `reading-${level}-01`, level, title, segments: [{ text }], translation, questions: [question], source };
}

export const reading: Reading[] = [
  article('N5', '朝の図書館', '今日は土曜日です。私は九時に図書館へ行きます。図書館で日本語の本を読みます。十二時に家へ帰ります。', 'Hôm nay là thứ Bảy. Tôi đến thư viện lúc chín giờ. Tôi đọc sách tiếng Nhật ở thư viện. Tôi về nhà lúc mười hai giờ.', { prompt: 'この人は図書館で何をしますか。', options: ['パンを食べます', '本を読みます', '水を買います', '映画を見ます'], answer: 1, explanation: 'Câu 図書館で日本語の本を読みます nói rõ người này đọc sách tiếng Nhật.' }),
  article('N4', '旅行の準備', '来週、友達と山へ行きます。山の近くには店が少ないので、前の日に飲み物を買っておきます。天気が悪かったら、山へは行かず、町の博物館を見学する予定です。', 'Tuần sau tôi sẽ cùng bạn đi lên núi. Vì gần núi có ít cửa hàng, tôi sẽ mua sẵn đồ uống vào ngày hôm trước. Nếu thời tiết xấu, chúng tôi dự định không lên núi mà tham quan bảo tàng trong thị trấn.', { prompt: '天気が悪い場合、どうしますか。', options: ['山で待ちます', '旅行を来月にします', '博物館へ行きます', '飲み物を買いません'], answer: 2, explanation: 'Điều kiện 天気が悪かったら dẫn đến kế hoạch tham quan bảo tàng.' }),
  article('N3', '小さな習慣', '仕事が忙しくなってから、長い時間勉強するのが難しくなった。そこで、通勤の電車で毎日十分だけ日本語の文章を読むようにした。短い時間でも続けたおかげで、以前より読むことへの抵抗が少なくなった。', 'Từ khi công việc bận hơn, việc học trong thời gian dài trở nên khó khăn. Vì vậy, tôi bắt đầu đọc văn bản tiếng Nhật mười phút mỗi ngày trên tàu đi làm. Nhờ duy trì dù thời gian ngắn, tôi thấy bớt ngại đọc hơn trước.', { prompt: '筆者が読むことに慣れてきた理由は何ですか。', options: ['短い時間でも毎日読んだから', '仕事を辞めたから', '通勤時間が長くなったから', '文章を全部暗記したから'], answer: 0, explanation: 'Người viết quy kết quả cho việc duy trì đọc mỗi ngày, dù chỉ trong thời gian ngắn.' }),
  article('N2', '予約枠の見直し', 'ある相談窓口では、利用者を待たせないために予約制を導入した。しかし、相談内容によって必要な時間が異なり、一律に二十分とした予約枠では対応しきれなかった。そこで、事前に相談内容を確認し、その内容に応じて枠の長さを変えることにした。', 'Một quầy tư vấn áp dụng chế độ đặt lịch để khách không phải chờ. Tuy nhiên, thời gian cần thiết khác nhau tùy nội dung tư vấn, nên các khung hẹn đồng loạt hai mươi phút không đáp ứng được. Vì vậy, họ quyết định kiểm tra trước nội dung và điều chỉnh độ dài khung hẹn tương ứng.', { prompt: '予約枠を変えることにした主な理由は何ですか。', options: ['利用者が予約を嫌ったため', '職員が減ったため', '二十分の相談が禁止されたため', '相談ごとに必要な時間が違うため'], answer: 3, explanation: 'Vấn đề là thời gian cần cho từng nội dung khác nhau; bài không nói khách phản đối hay giảm nhân viên.' }),
  article('N1', '数値と現場', '業務の効率を測る指標は、改善の手掛かりになる。ただし、処理件数だけを評価すれば、時間を要する複雑な相談への配慮が失われかねない。数値と現場の実態との乖離を避けるには、指標を廃止するのではなく、件数に表れない対応の質も踏まえて評価する必要がある。', 'Chỉ số đo hiệu suất công việc có thể gợi hướng cải thiện. Tuy nhiên, nếu chỉ đánh giá số vụ xử lý, sự quan tâm đến các trường hợp tư vấn phức tạp cần nhiều thời gian có nguy cơ bị mất đi. Để tránh khoảng cách giữa số liệu và thực tế, cần đánh giá cả chất lượng xử lý không thể hiện trong số lượng, thay vì bỏ các chỉ số.', { prompt: '筆者が求めている評価の方法はどれですか。', options: ['指標をすべて廃止する', '件数と対応の質の両方を考慮する', '複雑な相談を評価から除く', '件数だけで順位を決める'], answer: 1, explanation: 'Tác giả giữ vai trò của chỉ số nhưng yêu cầu xét thêm chất lượng xử lý ngoài số lượng.' }),
];

function dialogue(level: Level, title: string, transcript: string, translation: string, question: Question): Listening {
  return { id: `listening-${level}-01`, level, title, transcript, translation, question, source };
}

export const listening: Listening[] = [
  dialogue('N5', '待ち合わせ', '女：明日、何時に会いますか。男：十時はどうですか。女：いいですね。駅の前で会いましょう。', 'Nữ: Ngày mai chúng ta gặp lúc mấy giờ? Nam: Mười giờ được không? Nữ: Được đấy. Gặp trước nhà ga nhé.', { prompt: '二人は何時に会いますか。', options: ['九時', '十一時', '十時', '十二時'], answer: 2, explanation: 'Người nam đề nghị mười giờ và người nữ đồng ý.' }),
  dialogue('N4', '持っていく物', '男：明日のピクニック、お弁当を作りましょうか。女：お弁当は私が作ります。飲み物をお願いできますか。男：分かりました。今夜買っておきます。', 'Nam: Tôi làm cơm hộp cho buổi dã ngoại ngày mai nhé? Nữ: Tôi sẽ làm cơm hộp. Bạn lo đồ uống được không? Nam: Được. Tối nay tôi sẽ mua sẵn.', { prompt: '男の人は何を準備しますか。', options: ['飲み物', 'お弁当', '切符', '傘'], answer: 0, explanation: 'Sau lời đề nghị ban đầu, người nam nhận việc chuẩn bị đồ uống.' }),
  dialogue('N3', '資料の確認', '女：資料はもう送れますか。男：表の数字は確認しましたが、最後のページの住所が古いままです。女：では、そこを直してから送ってください。男：はい、すぐ直します。', 'Nữ: Có thể gửi tài liệu chưa? Nam: Tôi đã kiểm tra số liệu trong bảng nhưng địa chỉ ở trang cuối vẫn là địa chỉ cũ. Nữ: Vậy hãy sửa chỗ đó rồi gửi. Nam: Vâng, tôi sửa ngay.', { prompt: '男の人は送る前に何をしますか。', options: ['表を削除します', '資料を印刷します', '数字を増やします', '住所を直します'], answer: 3, explanation: 'Địa chỉ cũ cần được sửa trước khi gửi; số liệu đã được kiểm tra.' }),
  dialogue('N2', '研修の変更', '女：来月の研修は、全員同じ内容で進めますか。男：経験の差が大きいので、最初の説明だけ一緒にして、その後は経験に応じて二つのグループに分けましょう。女：分かりました。実習も各グループで行いますね。', 'Nữ: Buổi đào tạo tháng sau sẽ cùng một nội dung cho mọi người à? Nam: Kinh nghiệm chênh lệch lớn, nên chỉ phần giải thích đầu tiên làm chung; sau đó chia hai nhóm tùy kinh nghiệm. Nữ: Tôi hiểu. Phần thực hành cũng làm theo từng nhóm nhé.', { prompt: '全員が一緒に受けるのはどの部分ですか。', options: ['実習だけ', '最初の説明だけ', '研修の全体', '最後の試験だけ'], answer: 1, explanation: 'Người nam nói rõ 最初の説明だけ一緒にして; sau đó chia nhóm.' }),
  dialogue('N1', '制度の試行', '女：新制度は、試行の結果が良ければすぐ全店に導入しますか。男：数字だけでは判断できません。担当者への聞き取りも踏まえて、現場への負担を確認してから範囲を決めたいと思います。女：では、まず聞き取りの日程を調整します。', 'Nữ: Nếu kết quả thử nghiệm tốt, sẽ áp dụng ngay chế độ mới ở tất cả cửa hàng chứ? Nam: Không thể quyết định chỉ bằng số liệu. Tôi muốn xét cả ý kiến thu thập từ người phụ trách, kiểm tra gánh nặng tại hiện trường rồi mới quyết định phạm vi. Nữ: Vậy trước hết tôi sẽ sắp xếp lịch phỏng vấn.', { prompt: '男の人は導入範囲をどう決めたいと考えていますか。', options: ['数字が良ければ自動的に全店にする', '担当者の意見を聞かずに決める', '聞き取りと現場の負担も確認して決める', '試行をせずに一店舗だけにする'], answer: 2, explanation: 'Anh ấy muốn dùng cả ý kiến người phụ trách và kiểm tra gánh nặng thực tế để quyết định.' }),
];
